/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-11 08:58:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.History;
import model.User;
import service.BMIService;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.History");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("service.BMIService");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>FoodAnalyzer | Dashboard</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://unpkg.com/html5-qrcode\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        :root { --sidebar-bg: #111827; --accent: #3b82f6; }\r\n");
      out.write("        body { background-color: #f9fafb; font-family: 'Segoe UI', sans-serif; }\r\n");
      out.write("        .sidebar { width: 260px; height: 100vh; position: fixed; background: var(--sidebar-bg); color: white; }\r\n");
      out.write("        .main-content { margin-left: 260px; padding: 40px; }\r\n");
      out.write("        .nav-link { color: #9ca3af; padding: 12px 20px; border-radius: 8px; margin: 4px 15px; border: none; background: none; width: 85%; text-align: left;}\r\n");
      out.write("        .nav-link.active { background: var(--accent); color: white; }\r\n");
      out.write("        .nav-link:hover:not(.active) { background: #1f2937; color: white; }\r\n");
      out.write("        .card { border: none; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }\r\n");
      out.write("        #reader { width: 100%; border-radius: 12px; overflow: hidden; }\r\n");
      out.write("        .bmi-indicator { font-size: 2.5rem; font-weight: 800; color: var(--accent); }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    List<History> list = (List<History>) request.getAttribute("history");
    User user = (User) session.getAttribute("user");
    double bmi = BMIService.calculateBMI(user.getWeight(), user.getHeight());
    String bmiStatus = BMIService.getBMIStatus(bmi);
    
    int high = 0, med = 0, low = 0;
    if (list != null) {
        for (History x : list) {
            if (x.getScore() >= 80) high++;
            else if (x.getScore() >= 50) med++;
            else low++;
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar d-flex flex-column p-3 shadow-lg\">\r\n");
      out.write("    <div class=\"text-center py-4\">\r\n");
      out.write("        <h3 class=\"fw-bold text-primary\"><i class=\"fas fa-microchip me-2\"></i>FoodAnalyzer</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav nav-pills flex-column\" id=\"v-pills-tab\" role=\"tablist\">\r\n");
      out.write("        <button class=\"nav-link active mb-2\" data-bs-toggle=\"pill\" data-bs-target=\"#tab-home\"><i class=\"fas fa-house me-2\"></i> Overview</button>\r\n");
      out.write("        <button class=\"nav-link mb-2\" data-bs-toggle=\"pill\" data-bs-target=\"#tab-scan\" onclick=\"startScanner()\"><i class=\"fas fa-barcode me-2\"></i> Scanner</button>\r\n");
      out.write("        <button class=\"nav-link mb-2\" data-bs-toggle=\"pill\" data-bs-target=\"#tab-bmi\"><i class=\"fas fa-weight-scale me-2\"></i> BMI Tracker</button>\r\n");
      out.write("        <button class=\"nav-link mb-2\" data-bs-toggle=\"pill\" data-bs-target=\"#tab-history\"><i class=\"fas fa-clock-rotate-left me-2\"></i> History</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mt-auto p-3 bg-dark rounded mx-2 mb-3\">\r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("            <div class=\"flex-grow-1 overflow-hidden\">\r\n");
      out.write("                <p class=\"mb-0 small fw-bold text-truncate\">");
      out.print( user.getName() );
      out.write("</p>\r\n");
      out.write("                <p class=\"mb-0 x-small text-muted\" style=\"font-size: 0.7rem;\">");
      out.print( user.getEmail() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"logout\" class=\"text-danger ms-2\"><i class=\"fas fa-power-off\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"tab-content\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"tab-pane fade show active\" id=\"tab-home\">\r\n");
      out.write("            <h2 class=\"fw-bold mb-4\">Hello, ");
      out.print( user.getName().split(" ")[0] );
      out.write("! 👋</h2>\r\n");
      out.write("            <div class=\"row g-4 mb-5\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card p-4 border-start border-primary border-5\">\r\n");
      out.write("                        <p class=\"text-muted small fw-bold mb-1\">HEALTHY CHOICES</p>\r\n");
      out.write("                        <h2 class=\"m-0\">");
      out.print( high );
      out.write("</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card p-4 border-start border-warning border-5\">\r\n");
      out.write("                        <p class=\"text-muted small fw-bold mb-1\">MODERATE</p>\r\n");
      out.write("                        <h2 class=\"m-0\">");
      out.print( med );
      out.write("</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card p-4 border-start border-danger border-5\">\r\n");
      out.write("                        <p class=\"text-muted small fw-bold mb-1\">UNHEALTHY</p>\r\n");
      out.write("                        <h2 class=\"m-0\">");
      out.print( low );
      out.write("</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card p-4\">\r\n");
      out.write("                <h5 class=\"fw-bold mb-3\">Your Health Profile</h5>\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-3 border-end\">\r\n");
      out.write("                        <div class=\"bmi-indicator\">");
      out.print( String.format("%.1f", bmi) );
      out.write("</div>\r\n");
      out.write("                        <span class=\"badge bg-primary px-3 py-2\">");
      out.print( bmiStatus );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-9 ps-4\">\r\n");
      out.write("                        <p class=\"text-muted mb-0\">Weight: <b>");
      out.print( user.getWeight() );
      out.write(" kg</b></p>\r\n");
      out.write("                        <p class=\"text-muted mb-0\">Height: <b>");
      out.print( user.getHeight() );
      out.write(" m</b></p>\r\n");
      out.write("                        <button class=\"btn btn-sm btn-outline-primary mt-3\" onclick=\"document.querySelector('[data-bs-target=\\'#tab-bmi\\']').click()\">Update Stats</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"tab-pane fade\" id=\"tab-scan\">\r\n");
      out.write("            <h2 class=\"fw-bold mb-4\">Product Scanner</h2>\r\n");
      out.write("            <div class=\"row g-4\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <div class=\"card p-4\">\r\n");
      out.write("                        <h5 class=\"mb-3\"><i class=\"fas fa-camera me-2\"></i>Live Barcode Scan</h5>\r\n");
      out.write("                        <div id=\"reader\"></div>\r\n");
      out.write("                        <p class=\"small text-muted mt-3 text-center\">Center the barcode in the frame</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <div class=\"card p-4\">\r\n");
      out.write("                        <h5 class=\"mb-3\"><i class=\"fas fa-keyboard me-2\"></i>Manual Entry</h5>\r\n");
      out.write("                        <form action=\"product\" method=\"get\">\r\n");
      out.write("                            <input type=\"text\" name=\"barcode\" class=\"form-control form-control-lg mb-3\" placeholder=\"Enter barcode number...\" required>\r\n");
      out.write("                            <button class=\"btn btn-primary btn-lg w-100 shadow\">Analyze Content</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"tab-pane fade\" id=\"tab-bmi\">\r\n");
      out.write("            <h2 class=\"fw-bold mb-4\">Body Metrics</h2>\r\n");
      out.write("            <div class=\"card p-4 shadow-sm\" style=\"max-width: 500px;\">\r\n");
      out.write("                <form action=\"updateProfile\" method=\"post\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label fw-bold\">Current Weight (kg)</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.1\" name=\"weight\" class=\"form-control\" value=\"");
      out.print( user.getWeight() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label fw-bold\">Current Height (m)</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.01\" name=\"height\" class=\"form-control\" value=\"");
      out.print( user.getHeight() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary w-100 py-2\">Save and Recalculate</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"tab-pane fade\" id=\"tab-history\">\r\n");
      out.write("            <div class=\"card shadow-sm overflow-hidden\">\r\n");
      out.write("                <div class=\"card-header bg-white py-3 d-flex justify-content-between\">\r\n");
      out.write("                    <h5 class=\"m-0 fw-bold\">Recent History</h5>\r\n");
      out.write("                    <input type=\"text\" id=\"liveSearch\" class=\"form-control w-25 shadow-sm\" placeholder=\"Filter log...\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <table class=\"table table-hover align-middle mb-0\" id=\"histTable\">\r\n");
      out.write("                    <thead class=\"table-light\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th class=\"ps-4\">Product Name</th>\r\n");
      out.write("                            <th class=\"text-center\">Score</th>\r\n");
      out.write("                            <th>Category</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 if (list != null) { for (History h : list) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"ps-4 fw-bold\">");
      out.print( h.getProductName() );
      out.write("</td>\r\n");
      out.write("                            <td class=\"text-center\">\r\n");
      out.write("                                <span class=\"badge ");
      out.print( h.getScore() >= 50 ? "bg-primary" : "bg-secondary" );
      out.write("\">\r\n");
      out.write("                                    ");
      out.print( h.getScore() );
      out.write(" / 100\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td><span class=\"text-muted\">");
      out.print( h.getCategory() );
      out.write("</span></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // Scanner Logic\r\n");
      out.write("    let html5QrcodeScanner;\r\n");
      out.write("    function startScanner() {\r\n");
      out.write("        if(!html5QrcodeScanner) {\r\n");
      out.write("            html5QrcodeScanner = new Html5QrcodeScanner(\"reader\", { fps: 10, qrbox: 250 });\r\n");
      out.write("            html5QrcodeScanner.render((code) => {\r\n");
      out.write("                window.location.href = \"product?barcode=\" + code;\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Search Logic\r\n");
      out.write("    document.getElementById('liveSearch').addEventListener('keyup', function() {\r\n");
      out.write("        let val = this.value.toLowerCase();\r\n");
      out.write("        let rows = document.querySelectorAll('#histTable tbody tr');\r\n");
      out.write("        rows.forEach(r => r.style.display = r.innerText.toLowerCase().includes(val) ? '' : 'none');\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
