/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-11 08:12:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.History;

public final class history_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.History");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>User History</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: #f8f9fa; }\r\n");
      out.write("        .table-container { margin-top: 50px; }\r\n");
      out.write("        .card { border-radius: 15px; border: none; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }\r\n");
      out.write("        .table thead { background-color: #0d6efd; color: white; }\r\n");
      out.write("        .hover-row:hover { background-color: #e9ecef; transition: 0.3s; }\r\n");
      out.write("        .badge-score { font-size: 0.9rem; padding: 0.5em 0.8em; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container table-container\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-10\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header bg-white py-3 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                    <h4 class=\"mb-0 text-primary\"><i class=\"fas fa-history me-2\"></i>Activity History</h4>\r\n");
      out.write("                    <input type=\"text\" id=\"tableSearch\" class=\"form-control form-control-sm w-25\" placeholder=\"Search product...\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card-body p-0\">\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table table-hover mb-0\" id=\"historyTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th class=\"ps-4\">Product Name</th>\r\n");
      out.write("                                    <th class=\"text-center\">Score</th>\r\n");
      out.write("                                    <th class=\"text-center\">Status</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            ");

                                List<History> list = (List<History>) request.getAttribute("history");
                                if (list != null && !list.isEmpty()) {
                                    for (History h : list) {
                            
      out.write("\r\n");
      out.write("                                <tr class=\"hover-row\">\r\n");
      out.write("                                    <td class=\"ps-4 align-middle fw-semibold\">\r\n");
      out.write("                                        <i class=\"fas fa-box-open text-secondary me-2\"></i>");
      out.print( h.getProductName() );
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"text-center align-middle\">\r\n");
      out.write("                                        <span class=\"badge rounded-pill bg-info text-dark badge-score\">\r\n");
      out.write("                                            ");
      out.print( h.getScore() );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td class=\"text-center align-middle\">\r\n");
      out.write("                                        ");
 if(h.getScore() >= 50) { 
      out.write("\r\n");
      out.write("                                            <span class=\"text-success\"><i class=\"fas fa-check-circle\"></i> Passed</span>\r\n");
      out.write("                                        ");
 } else { 
      out.write("\r\n");
      out.write("                                            <span class=\"text-danger\"><i class=\"fas fa-times-circle\"></i> Review</span>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 
                                    } 
                                } else { 
                            
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=\"3\" class=\"text-center py-5 text-muted\">\r\n");
      out.write("                                        <i class=\"fas fa-folder-open fa-3x mb-3\"></i>\r\n");
      out.write("                                        <p>No history records found for your account.</p>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mt-3 text-center\">\r\n");
      out.write("                <a href=\"dashboard.jsp\" class=\"btn btn-outline-secondary btn-sm\">\r\n");
      out.write("                    <i class=\"fas fa-arrow-left me-1\"></i> Back to Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('tableSearch').addEventListener('keyup', function() {\r\n");
      out.write("        let value = this.value.toLowerCase();\r\n");
      out.write("        let rows = document.querySelectorAll('#historyTable tbody tr');\r\n");
      out.write("        rows.forEach(row => {\r\n");
      out.write("            row.style.display = row.innerText.toLowerCase().includes(value) ? '' : 'none';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
