/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-11 08:26:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login | Secure Portal</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        .login-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 15px 35px rgba(0,0,0,0.2);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .form-floating > label { color: #6c757d; }\r\n");
      out.write("        .btn-login {\r\n");
      out.write("            background: #764ba2;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-login:hover {\r\n");
      out.write("            background: #5a3782;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("        .input-group-text {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            border-left: none;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            border-color: #764ba2;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"login-card animate__animated animate__fadeInDown\">\r\n");
      out.write("    <div class=\"text-center mb-4\">\r\n");
      out.write("        <div class=\"bg-primary d-inline-block p-3 rounded-circle mb-3 shadow\">\r\n");
      out.write("            <i class=\"fas fa-lock text-white fa-2x\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h3 class=\"fw-bold text-dark\">Welcome Back</h3>\r\n");
      out.write("        <p class=\"text-muted small\">Please enter your credentials</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
 if(request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-danger d-flex align-items-center small py-2\" role=\"alert\">\r\n");
      out.write("            <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("            <div>");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form action=\"login\" method=\"post\" class=\"needs-validation\" novalidate>\r\n");
      out.write("        <div class=\"form-floating mb-3\">\r\n");
      out.write("            <input type=\"email\" name=\"email\" class=\"form-control\" id=\"email\" placeholder=\"name@example.com\" required>\r\n");
      out.write("            <label for=\"email\">Email address</label>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("            <div class=\"form-floating flex-grow-1\">\r\n");
      out.write("                <input type=\"password\" name=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Password\" style=\"border-right:none\" required>\r\n");
      out.write("                <label for=\"password\">Password</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"input-group-text border-start-0\" id=\"togglePassword\">\r\n");
      out.write("                <i class=\"fas fa-eye text-muted\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between mb-4\">\r\n");
      out.write("            <div class=\"form-check\">\r\n");
      out.write("                <input class=\"form-check-input\" type=\"checkbox\" id=\"remember\">\r\n");
      out.write("                <label class=\"form-check-label small\" for=\"remember\">Remember me</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"small text-decoration-none\">Forgot Password?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary btn-login w-100 mb-3\">\r\n");
      out.write("            SIGN IN <i class=\"fas fa-sign-in-alt ms-2\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <p class=\"text-center small text-muted\">\r\n");
      out.write("            Don't have an account? <a href=\"signup.jsp\" class=\"text-decoration-none fw-bold\">Register here</a>\r\n");
      out.write("        </p>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Password visibility toggle\r\n");
      out.write("    const togglePassword = document.querySelector('#togglePassword');\r\n");
      out.write("    const password = document.querySelector('#password');\r\n");
      out.write("\r\n");
      out.write("    togglePassword.addEventListener('click', function (e) {\r\n");
      out.write("        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';\r\n");
      out.write("        password.setAttribute('type', type);\r\n");
      out.write("        this.querySelector('i').classList.toggle('fa-eye-slash');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Bootstrap validation\r\n");
      out.write("    (() => {\r\n");
      out.write("        'use strict'\r\n");
      out.write("        const forms = document.querySelectorAll('.needs-validation')\r\n");
      out.write("        Array.from(forms).forEach(form => {\r\n");
      out.write("            form.addEventListener('submit', event => {\r\n");
      out.write("                if (!form.checkValidity()) {\r\n");
      out.write("                    event.preventDefault()\r\n");
      out.write("                    event.stopPropagation()\r\n");
      out.write("                }\r\n");
      out.write("                form.classList.add('was-validated')\r\n");
      out.write("            }, false)\r\n");
      out.write("        })\r\n");
      out.write("    })()\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
