# database configuration

hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/hfb04
hibernate.connection.username=root
hibernate.connection.password=root


#hibertnate properties

hibernate.dialect"=org.hibernate.dialect.MySQLDialect
hibernate.show_sql= true
hibernate.format_sql= true
hibernate.hbm2ddl.auto=none