/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-03-15 14:49:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.tca.entities.*;

public final class UpdateStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1773411535368L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("com.tca.entities");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-dark bg-dark fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"./\">Techno Comp Academy</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasDarkNavbar\" aria-controls=\"offcanvasDarkNavbar\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"offcanvas offcanvas-end text-bg-dark\" tabindex=\"-1\" id=\"offcanvasDarkNavbar\" aria-labelledby=\"offcanvasDarkNavbarLabel\">\r\n");
      out.write("      <div class=\"offcanvas-header\">\r\n");
      out.write("        <h5 class=\"offcanvas-title\" id=\"offcanvasDarkNavbarLabel\">Tca,Pune</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"offcanvas-body\">\r\n");
      out.write("        <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\"  href=\"./\">Home</a>\r\n");
      out.write("          </li>\r\n");
      out.write("           \r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" aria-current=\"page\"  href=\"./aboutus.jsp\">About Us</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("              Student\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("            \r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"./addstudent\">Add Students</a></li>\r\n");
      out.write("               <li><a class=\"dropdown-item\" href=\"./display\">Display Students</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"./update\">Update Students</a></li>\r\n");
      out.write("                 <li><a class=\"dropdown-item\" href=\"./delete\">Delete Students</a></li>\r\n");
      out.write("           \r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("         \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>1\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Update student</title>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    function  openUpdatePopup(trno){\r\n");
      out.write("    	var tr=document.getElementById(trno);\r\n");
      out.write(" 	   var td=tr.getElementsByTagName(\"td\");\r\n");
      out.write(" 	   \r\n");
      out.write(" 	   var srno=td[0].textContent;\r\n");
      out.write(" 	   var sname=td[1].textContent;\r\n");
      out.write(" 	   var sper=td[2].textContent;\r\n");
      out.write(" 	   \r\n");
      out.write(" \r\n");
      out.write(" 	   \r\n");
      out.write(" 	   var modalRno=document.getElementById(\"modalRno\");\r\n");
      out.write(" 	   var modalName=document.getElementById(\"modalName\");\r\n");
      out.write(" 	   var modalPer=document.getElementById(\"modalPer\");\r\n");
      out.write(" 	   \r\n");
      out.write(" 	   modalRno.value=srno;\r\n");
      out.write(" 	   modalName.value=sname;\r\n");
      out.write(" 	   modalPer.value=sper;\r\n");
      out.write(" 	  \r\n");
      out.write(" 	   new bootstrap.Modal(document.getElementById(\"updateModal\")).show();\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("       function modify(trno){\r\n");
      out.write("    	   var modalRno=document.getElementById(\"modalRno\");\r\n");
      out.write("     	   var modalName=document.getElementById(\"modalName\");\r\n");
      out.write("     	   var modalPer=document.getElementById(\"modalPer\");\r\n");
      out.write("     	   \r\n");
      out.write("     	   var updateSrno=modalRno.value;\r\n");
      out.write("     	   var updateSname=modalName.value;\r\n");
      out.write("     	   var updateSper=modalPer.value;\r\n");
      out.write("     	 \r\n");
      out.write("     	  fetch(\"http://localhost:8080/APP-Student-Mgmt-System/update\",\r\n");
      out.write("				  {\r\n");
      out.write("			        method:\"POST\",\r\n");
      out.write("			        body :new URLSearchParams({\"trno\":updateSrno, \"tname\":updateSname,\"tper\":updateSper})\r\n");
      out.write("				  }\r\n");
      out.write("		  )\r\n");
      out.write("		.then(response=>response.text())\r\n");
      out.write("		.then(data=>\r\n");
      out.write("		{\r\n");
      out.write("		   if(data.trim()==\"success\"){\r\n");
      out.write("		//	   alert(\" Record is updated succesfully!\");\r\n");
      out.write("		\r\n");
      out.write("		document.querySelector('#updateModal  .btn-close').click();\r\n");
      out.write("		\r\n");
      out.write("		swal(\"Good job!\", \"You clicked the button!\", \"success\")\r\n");
      out.write("		  .then( ()=>{\r\n");
      out.write("				  location.reload();\r\n");
      out.write("		  }\r\n");
      out.write("		  );\r\n");
      out.write("			  \r\n");
      out.write("			 \r\n");
      out.write("		   }\r\n");
      out.write("		   if(data.trim()==\"failed\"){\r\n");
      out.write("			   swal(\"Failure\", \"Failed to udate record !\", \"error\")\r\n");
      out.write("		   }\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		)\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		.catch(error=> console.error(\"Myerror while deleting roll number= \"+ updarteSrno));\r\n");
      out.write("				  \r\n");
      out.write("	\r\n");
      out.write("	 }\r\n");
      out.write("	   \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\" style=\"margin-top:100px;\"> \r\n");
      out.write("\r\n");
      out.write("   <h2 class=\"text-center text-primary mt-3 mt-5\"> Student Information</h2>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container-fluid d-flex justify-content-end\">\r\n");
      out.write("  \r\n");
      out.write("  <form  class=\"d-flex  mb-4\" role=\"search\" method=\"GET\" action=\"./delete\">\r\n");
      out.write("     <input  class=\"form-control me-3\" placeholder=\"Search Here\" type=\"search\"  name=\"srno\">\r\n");
      out.write("     <input class=\"btn btn-outline-success me-3\" type=\"submit\" name=\"sbtn\" value=\"Search\" >\r\n");
      out.write("       <input class=\"btn btn-outline-success\" type=\"submit\" name=\"sbtn\" value=\"Refresh\" >\r\n");
      out.write("       \r\n");
      out.write("  </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("  <br>\r\n");
      out.write("  \r\n");
      out.write("<table class=\"table table-hover table-bordered text-center\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr class=\"table-primary\">\r\n");
      out.write("    <th>Rno</th> <th>Name</th> <th>Percentage</th> <th>Action</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("     ");

     
     List<Student> L = (List<Student>)request.getAttribute("students");
    
     if(L.isEmpty()){
   
      out.write("\r\n");
      out.write("    	 <tr>	 \r\n");
      out.write("    	 <td class=\"text-danger bg-danger-subtle\" colspan=\"4\">No Data Found !!!</td>\r\n");
      out.write("    	 </tr>\r\n");
      out.write("   ");

     }
     else{
     for(Student s : L){
   
      out.write("\r\n");
      out.write("   \r\n");
      out.write("     <tr id=\"");
      out.print( s.getRno() );
      out.write("\">\r\n");
      out.write("      <td>");
      out.print( s.getRno() );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( s.getName() );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( s.getPer() );
      out.write("</td>\r\n");
      out.write("    <td>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" onclick=\"openUpdatePopup(");
      out.print( s.getRno() );
      out.write(")\">Update</button>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" ");

     }
     }
     
      out.write("\r\n");
      out.write("     \r\n");
      out.write(" </table>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <!-- -Modal -->\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"modal\" tabindex=\"-1\" id=\"updateModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("    \r\n");
      out.write("    <!--Modal header-->\r\n");
      out.write("      <div class=\"modal-header bg-primary text-white\">\r\n");
      out.write("        <h5 class=\"modal-title\">Update Student</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!--modal body-->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <div>\r\n");
      out.write("         \r\n");
      out.write("         <label class=\"form-label\">Roll Number</label>\r\n");
      out.write("         <input class=\"form-control\" type=\"text\" id=\"modalRno\" readonly>\r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("             <label class=\"form-label\">Name</label>\r\n");
      out.write("         <input class=\"form-control\" type=\"text\" id=\"modalName\">\r\n");
      out.write("         <div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("             <label class=\"form-label\">Percentage</label>\r\n");
      out.write("         <input class=\"form-control\" type=\"text\" id=\"modalPer\">\r\n");
      out.write("         <div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!--modal footer-->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" onclick=\"modify()\"> Update changes</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
