/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-10 04:41:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>Multi User Chat</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body { background:#0f172a; }\r\n");
      out.write("\r\n");
      out.write(".chat-box {\r\n");
      out.write("    height: 80vh;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    background: #020617;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".msg {\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    margin:5px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    max-width:60%;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".me { background:#22c55e; margin-left:auto; }\r\n");
      out.write(".other { background:#334155; margin-right:auto; }\r\n");
      out.write("\r\n");
      out.write(".username {\r\n");
      out.write("    font-size:12px;\r\n");
      out.write("    opacity:0.7;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("let username = localStorage.getItem(\"username\");\r\n");
      out.write("\r\n");
      out.write("if(!username){\r\n");
      out.write("    username = prompt(\"Enter your name:\");\r\n");
      out.write("    localStorage.setItem(\"username\", username);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadMessages(){\r\n");
      out.write("    fetch(\"FetchServlet\")\r\n");
      out.write("    .then(res => res.text())\r\n");
      out.write("    .then(data => {\r\n");
      out.write("\r\n");
      out.write("        let chat = document.getElementById(\"chat\");\r\n");
      out.write("        chat.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("        let lines = data.split(\"\\n\");\r\n");
      out.write("\r\n");
      out.write("        lines.forEach(line => {\r\n");
      out.write("            if(line.trim() !== \"\"){\r\n");
      out.write("\r\n");
      out.write("                let parts = line.split(\":\");\r\n");
      out.write("                let user = parts[0];\r\n");
      out.write("                let msg = parts.slice(1).join(\":\");\r\n");
      out.write("\r\n");
      out.write("                let div = document.createElement(\"div\");\r\n");
      out.write("                div.classList.add(\"msg\");\r\n");
      out.write("\r\n");
      out.write("                if(user === username){\r\n");
      out.write("                    div.classList.add(\"me\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    div.classList.add(\"other\");\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                div.innerHTML = \r\n");
      out.write("                    \"<div class='username'>\" + user + \"</div>\" +\r\n");
      out.write("                    \"<div>\" + msg + \"</div>\";\r\n");
      out.write("\r\n");
      out.write("                chat.appendChild(div);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        chat.scrollTop = chat.scrollHeight;\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendMsg(){\r\n");
      out.write("    let msg = document.getElementById(\"msg\").value;\r\n");
      out.write("\r\n");
      out.write("    fetch(\"ChatServlet\",{\r\n");
      out.write("        method:\"POST\",\r\n");
      out.write("        headers:{\"Content-Type\":\"application/x-www-form-urlencoded\"},\r\n");
      out.write("        body:\"username=\"+username+\"&message=\"+msg\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"msg\").value=\"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("setInterval(loadMessages,1000);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"loadMessages()\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-3\">\r\n");
      out.write("\r\n");
      out.write("```\r\n");
      out.write("<h3 class=\"text-white text-center\">💬 Multi User Chat</h3>\r\n");
      out.write("\r\n");
      out.write("<div id=\"chat\" class=\"chat-box\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"input-group mt-2\">\r\n");
      out.write("    <input type=\"text\" id=\"msg\" class=\"form-control\">\r\n");
      out.write("    <button class=\"btn btn-success\" onclick=\"sendMsg()\">Send</button>\r\n");
      out.write("</div>\r\n");
      out.write("```\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
